import React, { useState } from "react";
import { ChevronDown, Plus, Minus } from "lucide-react";
import { ArrowRightIcon } from "@radix-ui/react-icons";
import { cn } from "@/lib/utils";
import AnimatedShinyText from "../magicui/animated-shiny-text";

const FAQItem = ({ question, answer, isOpen, onClick }) => (
  <div className="mb-4">
    <div className="bg-white bg-opacity-10 min-h-[5rem] backdrop-filter backdrop-blur-lg rounded-3xl p-4 overflow-hidden shadow-lg transition-all duration-300 ease-in-out">
      <button
        className="flex justify-between items-center w-full text-left p-4"
        onClick={onClick}
      >
        <span className="text-sm font-medium text-black">{question}</span>
        {isOpen ? (
          <Minus className="w-4 h-4 text-black" />
        ) : (
          <Plus className="w-4 h-4 text-black" />
        )}
      </button>
      <div
        className={`overflow-hidden transition-all duration-300 ease-in-out ${
          isOpen ? "max-h-40 opacity-100" : "max-h-0 opacity-0"
        }`}
      >
        <div className="p-4 text-sm text-gray-400 font-light bg-white bg-opacity-5">
          {answer}
        </div>
      </div>
    </div>
  </div>
);

const FAQSection = () => {
  const [openQuestion, setOpenQuestion] = useState(null);

  const questions = [
    {
      question: "What is a Website AI CREATE?",
      answer:
        "Website AI CREATE is an advanced artificial intelligence tool designed to assist in creating high-quality and unique website content. It uses natural language processing and machine learning to generate various types of web content.",
    },
    {
      question: "What types of content can the AI generate?",
      answer:
        "The AI can generate a wide range of content including blog posts, product descriptions, meta descriptions, headlines, and other types of web copy. It's versatile and can adapt to different writing styles and tones.",
    },
    {
      question: "Is the generated content plagiarism-free?",
      answer:
        "Yes, the content generated by Website AI CREATE is original and plagiarism-free. The AI creates unique content based on the input and parameters you provide, ensuring that it doesn't copy existing text from the internet.",
    },
    {
      question: "How long does it take to generate content?",
      answer:
        "The generation time varies depending on the length and complexity of the content requested. Typically, short pieces can be generated in seconds, while longer, more detailed content might take a few minutes.",
    },
    {
      question: "Is my data secure when using the AI?",
      answer:
        "We take data security very seriously. All interactions with the AI are encrypted, and we do not store your input or generated content longer than necessary to provide the service. Your data is never shared with third parties.",
    },
  ];

  const halfLength = Math.ceil(questions.length / 2);

  return (
    <div className="max-w-7xl mx-auto px-4 py-12 mt-24">
      <div className="flex flex-col md:flex-row items-start justify-between">
        <div className="w-full md:w-1/3 space-y-4">
          {questions.slice(0, halfLength).map((item, index) => (
            <FAQItem
              key={index}
              question={item.question}
              answer={item.answer}
              isOpen={openQuestion === index}
              onClick={() =>
                setOpenQuestion(openQuestion === index ? null : index)
              }
            />
          ))}
        </div>

        <div className="w-full md:w-1/3 text-center pt-12 px-4 my-8 md:my-0 ">
          <h2 className="text-4xl font-bold mb-4">
            <span className="bg-clip-text text-transparent bg-gradient-to-br from-yellow-400 to-orange-600">
              Frequently
            </span>
            <br />
            Ask Question
          </h2>
          <p className="text-gray-400 font-light mb-8">
            Some questions to us by our first time users before using
          </p>
          <div
            className={cn(
              "group rounded-full hidden md:block border border-black/5 bg-neutral-100 max-w-[16rem] ml-auto mr-auto text-base text-white transition-all ease-in hover:cursor-pointer hover:bg-neutral-200 dark:border-white/5 dark:bg-neutral-900 dark:hover:bg-neutral-800"
            )}
          >
            <AnimatedShinyText className="inline-flex items-center justify-center px-4 py-2 transition ease-out hover:text-neutral-600 hover:duration-300 hover:dark:text-neutral-400">
              <span>✨ Ask Some Question</span>

              <ArrowRightIcon className="ml-1 size-3 transition-transform duration-300 ease-in-out group-hover:translate-x-0.5" />
            </AnimatedShinyText>
          </div>
        </div>

        <div className="w-full md:w-1/3 space-y-4">
          {questions.slice(halfLength).map((item, index) => (
            <FAQItem
              key={index + halfLength}
              question={item.question}
              answer={item.answer}
              isOpen={openQuestion === index + halfLength}
              onClick={() =>
                setOpenQuestion(
                  openQuestion === index + halfLength
                    ? null
                    : index + halfLength
                )
              }
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQSection;
